<%@ Page Language="C#" AutoEventWireup="true" CodeFile="01-States_SqlDataSource.aspx.cs" Inherits="AuthorManager" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" >
<head runat="server">
    <title>Vendors by State</title>
    <link href="StyleSheet.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <div style="background-color: #FFE0C0; height: 100px; width: 601px; padding: 10px">
			<br />
			<asp:Label id="Label1" runat="server" Width="99px" Height="19px">Select State:</asp:Label>
			<asp:DropDownList id="ddlStates" runat="server" Width="187px" Height="21px" AutoPostBack="True" DataSourceID="sqlGetStates" DataTextField="StateName" DataValueField="StateAbbreviation" OnSelectedIndexChanged="ddlStates_SelectedIndexChanged" ></asp:DropDownList>&nbsp;&nbsp;&nbsp;
			&nbsp;
			<br />
			<asp:SqlDataSource ID="sqlGetStates" runat="server" ConnectionString="<%$ ConnectionStrings:MyDbConnectionString %>" SelectCommand="SELECT [StateName], [StateAbbreviation] FROM [States]"></asp:SqlDataSource>
			&nbsp;
            <br /><br />
			<asp:Label ID="Label2" runat="server"></asp:Label>
			</div>
		<br />
		<div style="background-color: #E0E0E0; height: 392px; width: 601px; padding: 10px">		
				
			<asp:SqlDataSource ID="sqlGetVendors" runat="server" ConnectionString="<%$ ConnectionStrings:MyDbConnectionString %>" SelectCommand="SELECT * FROM [Vendors] WHERE ([State] = @State)" DeleteCommand="DELETE FROM [Vendors] WHERE [VendorID] = @VendorID" InsertCommand="INSERT INTO [Vendors] ([VendorID], [Name], [Address], [City], [State], [Zip]) VALUES (@VendorID, @Name, @Address, @City, @State, @Zip,)" UpdateCommand="UPDATE [Vendors] SET [Name] = @Name, [Address] = @Address, [City] = @City, [State] = @State, [Zip] = @Zip WHERE [VendorID] = @VendorID">
                <SelectParameters>
                    <asp:ControlParameter ControlID="ddlStates" Name="State" PropertyName="SelectedValue" Type="String" />
                </SelectParameters>
                <DeleteParameters>
                    <asp:Parameter Name="VendorID" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="VendorID" Type="String" />
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Address" Type="String" />
                    <asp:Parameter Name="City" Type="String" />
                    <asp:Parameter Name="State" Type="String" />
                    <asp:Parameter Name="Zip" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Name" Type="String" />
                    <asp:Parameter Name="Address" Type="String" />
                    <asp:Parameter Name="City" Type="String" />
                    <asp:Parameter Name="State" Type="String" />
                    <asp:Parameter Name="Zip" Type="String" />
                    <asp:Parameter Name="VendorID" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
            <br />
            <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" CellPadding="4" DataSourceID="sqlGetVendors" ForeColor="#333333" GridLines="None" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <Columns>
                    <asp:CommandField ShowSelectButton="True" />
                    <asp:BoundField DataField="VendorID" HeaderText="VendorID" SortExpression="VendorID" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="City" HeaderText="City" SortExpression="City" />
                    <asp:BoundField DataField="State" HeaderText="State" SortExpression="State" />
                    <asp:BoundField DataField="Country" HeaderText="Country" SortExpression="Country" />
                    <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
                    <asp:BoundField DataField="Zip" HeaderText="Zip" SortExpression="Zip" />
                </Columns>
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
            <br />
            <br />
				
			<br />
			
			<asp:Label id="lblResults" runat="server" Width="575px" Height="56px" Font-Bold="True"></asp:Label>
			<br />
			<br />
			
		</div>
    </div>
    </form>
</body>
</html>
